{pkgs}: {
  deps = [
    pkgs.gradle
    pkgs.libsecret
    pkgs.gnome-keyring
    pkgs.libgbm
    pkgs.xorg.xorgserver
    pkgs.xorg.libxcb
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libX11
    pkgs.libxkbcommon
    pkgs.alsa-lib
    pkgs.mesa
    pkgs.libdrm
    pkgs.dbus
    pkgs.cups
    pkgs.cairo
    pkgs.pango
    pkgs.at-spi2-atk
    pkgs.atk
    pkgs.nspr
    pkgs.nss
    pkgs.gtk3
    pkgs.glib
    pkgs.jdk17
    pkgs.noto-fonts-color-emoji
    pkgs.chromium
    pkgs.mysql80
  ];
}
