<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        @page { margin: 15mm 15mm 18mm 15mm; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 10pt; color: #000; }
        h1 { font-size: 14pt; margin: 0 0 6pt 0; }
        .meta { font-size: 8pt; color: #555; margin-bottom: 10pt; }
        table { width: 100%; border-collapse: collapse; margin-top: 8pt; }
        th { background: #e5e7eb; text-align: left; font-weight: bold; padding: 5pt 6pt; border: 1px solid #999; font-size: 9pt; }
        td { padding: 4pt 6pt; border: 1px solid #ccc; font-size: 9pt; }
        td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
        tfoot td { background: #f3f4f6; font-weight: bold; }
        .footer { position: fixed; bottom: -10mm; left: 0; right: 0; text-align: center; font-size: 7pt; color: #888; }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <div class="meta">
        Generated: {{ now()->format('Y-m-d H:i:s') }}
        @if($companyId ?? false) · Company: #{{ $companyId }}@endif
        @if($branchId ?? false) · Branch: #{{ $branchId }}@endif
    </div>

    <table>
        <thead>
            <tr>
                @foreach($headers as $i => $h)
                    <th class="{{ $i === 0 ? '' : 'num' }}">{{ $h }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($excelRows as $row)
                <tr>
                    @foreach($row as $i => $cell)
                        <td class="{{ $i === 0 ? '' : 'num' }}">{{ is_numeric($cell) && $i > 0 ? number_format((float)$cell, 2) : $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($headers) }}" style="text-align:center; padding:12pt;">No data.</td></tr>
            @endforelse
        </tbody>
        @if(isset($totals))
        <tfoot>
            <tr>
                @php $tvals = array_values($totals); @endphp
                <td>TOTALS</td>
                @for($i = 1; $i < count($headers); $i++)
                    <td class="num">{{ isset($tvals[$i-1]) && is_numeric($tvals[$i-1]) ? number_format((float)$tvals[$i-1], 2) : ($tvals[$i-1] ?? '-') }}</td>
                @endfor
            </tr>
        </tfoot>
        @endif
    </table>

    <div class="footer">TaxNest · {{ config('app.url', 'taxnest.com.pk') }} · Generated by Admin Reports</div>
</body>
</html>
