<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Compliance Certificate - {{ $company->name }}</title>
    <style>
        body { font-family: 'Georgia', serif; margin: 0; padding: 40px; background: #fff; color: #333; }
        .certificate { max-width: 800px; margin: 0 auto; border: 3px solid {{ $badgeColor }}; padding: 60px; position: relative; }
        .certificate::before { content: ''; position: absolute; top: 8px; left: 8px; right: 8px; bottom: 8px; border: 1px solid {{ $badgeColor }}; pointer-events: none; }
        .header { text-align: center; margin-bottom: 40px; }
        .logo { font-size: 14px; text-transform: uppercase; letter-spacing: 4px; color: #10b981; margin-bottom: 10px; }
        .title { font-size: 32px; font-weight: bold; color: #1f2937; margin: 10px 0; }
        .subtitle { font-size: 14px; color: #6b7280; text-transform: uppercase; letter-spacing: 2px; }
        .divider { width: 100px; height: 3px; background: {{ $badgeColor }}; margin: 30px auto; }
        .body { text-align: center; }
        .company-name { font-size: 28px; font-weight: bold; color: #1f2937; margin: 20px 0; }
        .ntn { font-size: 14px; color: #6b7280; margin-bottom: 30px; }
        .score-container { display: inline-block; margin: 20px auto; padding: 20px 40px; border: 2px solid {{ $badgeColor }}; border-radius: 12px; }
        .score-label { font-size: 12px; text-transform: uppercase; letter-spacing: 2px; color: #6b7280; }
        .score-value { font-size: 48px; font-weight: bold; color: {{ $badgeColor }}; }
        .score-category { font-size: 18px; font-weight: bold; color: {{ $badgeColor }}; text-transform: uppercase; letter-spacing: 2px; margin-top: 5px; }
        .month-label { font-size: 16px; color: #4b5563; margin: 20px 0; }
        .description { font-size: 14px; color: #6b7280; line-height: 1.8; max-width: 500px; margin: 20px auto; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; }
        .footer p { font-size: 12px; color: #9ca3af; margin: 4px 0; }
        .seal { display: inline-block; width: 80px; height: 80px; border: 2px solid {{ $badgeColor }}; border-radius: 50%; line-height: 80px; text-align: center; font-size: 11px; font-weight: bold; color: {{ $badgeColor }}; text-transform: uppercase; margin: 20px 0; }
        @media print { body { padding: 0; } .certificate { border-width: 2px; } }
    </style>
</head>
<body>
    <div class="certificate">
        <div class="header">
            <div class="logo">TaxNest</div>
            <div class="title">Compliance Certificate</div>
            <div class="subtitle">Federal Board of Revenue - Tax Compliance</div>
        </div>

        <div class="divider"></div>

        <div class="body">
            <p style="font-size: 14px; color: #6b7280;">This is to certify that</p>
            <div class="company-name">{{ $company->name }}</div>
            <div class="ntn">NTN: {{ $company->ntn }}</div>

            <p style="font-size: 14px; color: #6b7280;">has achieved a compliance score of</p>

            <div class="score-container">
                <div class="score-label">Compliance Score</div>
                <div class="score-value">{{ $score }}</div>
                <div class="score-category">{{ $category }}</div>
            </div>

            <div class="month-label">For the period of <strong>{{ $monthLabel }}</strong></div>

            <div class="description">
                This certificate confirms that the above-named company has maintained
                tax compliance standards as measured by TaxNest's Compliance Risk Engine,
                which evaluates FBR submission success rates, retry ratios, draft aging,
                and failure ratios.
            </div>

            <div class="seal">VERIFIED</div>
        </div>

        <div class="footer">
            <p>Generated by TaxNest Compliance Control Center</p>
            <p>Certificate ID: CERT-{{ $company->id }}-{{ now()->format('Ymd-His') }}</p>
            <p>Generated on: {{ now()->format('F d, Y \a\t h:i A') }}</p>
        </div>
    </div>
</body>
</html>
