<style>
@keyframes fblPop { from { opacity: 0; transform: scale(0.92); } to { opacity: 1; transform: scale(1); } }
.fbl-a { animation: fblPop 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) forwards; }
.fbl-1 { animation-delay: 0ms; } .fbl-2 { animation-delay: 50ms; } .fbl-3 { animation-delay: 100ms; } .fbl-4 { animation-delay: 150ms; }
.fbl-tile { border-radius: 20px; padding: 20px; position: relative; overflow: hidden; transition: all 0.25s; }
.fbl-tile:hover { transform: translateY(-4px) scale(1.02); }
.fbl-tile::after { content: ''; position: absolute; inset: 0; background: linear-gradient(135deg, rgba(255,255,255,0.15) 0%, transparent 60%); pointer-events: none; }
.fbl-ring { width: 60px; height: 60px; border-radius: 50%; display: flex; align-items: center; justify-content: center; position: relative; }
.fbl-ring::before { content: ''; position: absolute; inset: 0; border-radius: 50%; border: 3px solid rgba(255,255,255,0.15); }
.fbl-g { background: rgba(255,255,255,0.85); backdrop-filter: blur(16px); border: 1px solid rgba(0,0,0,0.04); border-radius: 16px; }
.dark .fbl-g { background: rgba(17,24,39,0.85); border-color: rgba(255,255,255,0.06); }
</style>
<div class="space-y-5">
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 fbl-a fbl-1">
        <div><p class="text-[10px] font-bold text-blue-600 dark:text-blue-400 uppercase tracking-widest">FBR POS Dashboard</p><h1 class="text-xl font-black text-gray-900 dark:text-white mt-0.5">{{ $company->name ?? 'Business' }}</h1><p class="text-[11px] text-gray-400 mt-0.5">{{ now()->format('l, d M Y') }}</p></div>
        <div class="flex items-center gap-2">
            @include('fbr-pos.dashboard-styles._style-picker')
            <div x-data="{ fbrEnabled: {{ $fbrReportingStatus ? 'true' : 'false' }}, loading: false }" class="flex items-center gap-2 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl px-3 py-1.5"><span class="text-[10px] font-bold text-gray-500">FBR</span><button @click="loading=true; fetch('{{ route('fbrpos.api.toggle-fbr-reporting') }}', {method:'POST', headers:{'X-CSRF-TOKEN':'{{ csrf_token() }}','Content-Type':'application/json'}}).then(r=>r.json()).then(d=>{fbrEnabled=d.enabled; loading=false;})" :class="fbrEnabled ? 'bg-blue-600' : 'bg-gray-300'" class="relative inline-flex h-5 w-9 rounded-full transition-colors" :disabled="loading"><span :class="fbrEnabled ? 'translate-x-4' : 'translate-x-0'" class="pointer-events-none inline-block h-4 w-4 rounded-full bg-white shadow mt-0.5 ml-0.5 transition"></span></button><span x-text="fbrEnabled ? 'ON' : 'OFF'" :class="fbrEnabled ? 'text-blue-600' : 'text-red-500'" class="text-[9px] font-bold"></span></div>
            <a href="{{ route('fbrpos.create') }}" class="inline-flex items-center gap-1.5 px-4 py-2 bg-blue-600 text-white text-[11px] font-bold rounded-xl hover:bg-blue-700 transition"><svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg> New Sale</a>
        </div>
    </div>
    @if($company->fbr_pos_id)<div class="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-xl px-4 py-2.5 flex items-center gap-3 fbl-a fbl-1"><div class="w-7 h-7 rounded-lg bg-blue-600 flex items-center justify-center"><svg class="w-3.5 h-3.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"/></svg></div><p class="text-[10px] font-bold text-blue-800 dark:text-blue-300">FBR Integrated — POS #{{ $company->fbr_pos_id }}</p></div>@endif
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 fbl-a fbl-2">
        <div class="fbl-tile bg-gradient-to-br from-blue-500 via-blue-600 to-indigo-700 shadow-xl shadow-blue-500/25"><div class="relative z-10"><div class="fbl-ring mx-auto mb-2"><span class="text-white font-black text-xs z-10">Rs</span></div><p class="text-center text-lg font-black text-white">{{ number_format($todayStats->revenue ?? 0) }}</p><p class="text-center text-[8px] text-white/60 font-bold mt-1 uppercase">Today's Sales</p></div></div>
        <div class="fbl-tile bg-gradient-to-br from-indigo-500 via-indigo-600 to-purple-700 shadow-xl shadow-indigo-500/25"><div class="relative z-10"><div class="fbl-ring mx-auto mb-2"><span class="text-white font-black text-lg z-10">{{ $todayStats->count ?? 0 }}</span></div><p class="text-center text-lg font-black text-white">Orders</p><p class="text-center text-[8px] text-white/60 font-bold mt-1 uppercase">Today</p></div></div>
        <div class="fbl-tile bg-gradient-to-br from-emerald-500 via-emerald-600 to-teal-700 shadow-xl shadow-emerald-500/25"><div class="relative z-10"><div class="fbl-ring mx-auto mb-2"><span class="text-white font-black text-lg z-10">{{ $fbrSubmitted }}</span></div><p class="text-center text-lg font-black text-white">Submitted</p><p class="text-center text-[8px] text-white/60 font-bold mt-1 uppercase">FBR</p></div></div>
        <div class="fbl-tile bg-gradient-to-br from-amber-500 via-orange-500 to-red-600 shadow-xl shadow-amber-500/25"><div class="relative z-10"><div class="fbl-ring mx-auto mb-2"><span class="text-white font-black text-lg z-10">{{ $fbrPending }}</span></div><p class="text-center text-lg font-black text-white">Pending</p><p class="text-center text-[8px] text-white/60 font-bold mt-1 uppercase">FBR</p></div></div>
    </div>
    <div class="grid grid-cols-3 gap-3 fbl-a fbl-3">
        <div class="fbl-g p-4"><p class="text-[9px] font-bold text-gray-400 uppercase">Monthly Revenue</p><p class="text-lg font-black text-gray-900 dark:text-white mt-1">Rs.{{ number_format($monthStats->revenue ?? 0) }}</p><p class="text-[9px] text-gray-400">{{ $monthStats->count ?? 0 }} txns</p></div>
        <div class="fbl-g p-4"><p class="text-[9px] font-bold text-gray-400 uppercase">Monthly Tax</p><p class="text-lg font-black text-gray-900 dark:text-white mt-1">Rs.{{ number_format($monthStats->tax ?? 0) }}</p></div>
        <div class="fbl-g p-4"><p class="text-[9px] font-bold text-gray-400 uppercase">Today's Tax</p><p class="text-lg font-black text-gray-900 dark:text-white mt-1">Rs.{{ number_format($todayStats->tax ?? 0) }}</p></div>
    </div>
    <div class="fbl-g overflow-hidden fbl-a fbl-4">
        <div class="px-4 py-3 border-b border-gray-100 dark:border-gray-800 flex items-center justify-between"><h3 class="text-[11px] font-bold text-gray-900 dark:text-white uppercase">Recent Transactions</h3><a href="{{ route('fbrpos.transactions') }}" class="text-[10px] font-bold text-blue-600">VIEW ALL</a></div>
        <div class="overflow-x-auto"><table class="w-full"><thead><tr class="bg-gray-50/60 dark:bg-gray-800/30"><th class="text-left text-[9px] text-gray-400 font-bold uppercase py-2 px-4">Invoice</th><th class="text-left text-[9px] text-gray-400 font-bold uppercase py-2 px-3">Customer</th><th class="text-right text-[9px] text-gray-400 font-bold uppercase py-2 px-3">Amount</th><th class="text-center text-[9px] text-gray-400 font-bold uppercase py-2 px-3">FBR</th><th class="text-left text-[9px] text-gray-400 font-bold uppercase py-2 px-4">Date</th></tr></thead><tbody>
            @forelse($recentTransactions as $txn)
            <tr class="border-b border-gray-50 dark:border-gray-800/50 hover:bg-blue-50/30 transition"><td class="py-2 px-4"><a href="{{ route('fbrpos.show', $txn->id) }}" class="text-[11px] font-bold text-blue-600">{{ $txn->invoice_number }}</a></td><td class="py-2 px-3 text-[11px] text-gray-600 dark:text-gray-400">{{ $txn->customer_name ?? 'Walk-in' }}</td><td class="py-2 px-3 text-right text-[11px] font-bold text-gray-900 dark:text-white">Rs.{{ number_format($txn->total_amount, 2) }}</td><td class="py-2 px-3 text-center"><span class="text-[8px] font-bold px-1.5 py-0.5 rounded-full {{ $txn->fbr_status === 'submitted' ? 'bg-green-100 text-green-700' : ($txn->fbr_status === 'failed' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700') }}">{{ ucfirst($txn->fbr_status ?? 'pending') }}</span></td><td class="py-2 px-4 text-[10px] text-gray-400">{{ $txn->created_at->format('d M h:i A') }}</td></tr>
            @empty<tr><td colspan="5" class="py-8 text-center text-[11px] text-gray-400">No transactions yet</td></tr>@endforelse
        </tbody></table></div>
    </div>
</div>
