<style>
@keyframes fbs { from { opacity: 0; transform: translateY(16px); } to { opacity: 1; transform: translateY(0); } }
.fbs-a { animation: fbs 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards; }
.fbs-1 { animation-delay: 0ms; } .fbs-2 { animation-delay: 80ms; } .fbs-3 { animation-delay: 160ms; } .fbs-4 { animation-delay: 240ms; }
.fbs-hero { background: linear-gradient(145deg, #0f172a 0%, #1e293b 50%, #334155 100%); border-radius: 24px; position: relative; overflow: hidden; }
.fbs-hero::before { content: ''; position: absolute; top: -50%; right: -30%; width: 70%; height: 140%; background: radial-gradient(circle, rgba(99,102,241,0.08) 0%, transparent 60%); }
.fbs-g { background: rgba(255,255,255,0.9); backdrop-filter: blur(20px); border: 1px solid rgba(0,0,0,0.04); border-radius: 16px; }
.dark .fbs-g { background: rgba(15,23,42,0.9); border-color: rgba(255,255,255,0.06); }
</style>
<div class="space-y-5">
    <div class="fbs-hero p-6 sm:p-8 fbs-a fbs-1">
        <div class="relative z-10">
            <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
                <div><p class="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em]">{{ now()->format('l, d M Y') }}</p><h1 class="text-2xl sm:text-3xl font-black text-white mt-2">FBR POS</h1><p class="text-sm text-slate-400 mt-1">{{ $company->name ?? 'Business' }}</p></div>
                <div class="flex items-center gap-2">
                    @include('fbr-pos.dashboard-styles._style-picker')
                    <div x-data="{ fbrEnabled: {{ $fbrReportingStatus ? 'true' : 'false' }}, loading: false }" class="flex items-center gap-2 bg-white/5 border border-white/10 rounded-xl px-3 py-1.5"><span class="text-[10px] font-bold text-slate-400">FBR</span><button @click="loading=true; fetch('{{ route('fbrpos.api.toggle-fbr-reporting') }}', {method:'POST', headers:{'X-CSRF-TOKEN':'{{ csrf_token() }}','Content-Type':'application/json'}}).then(r=>r.json()).then(d=>{fbrEnabled=d.enabled; loading=false;})" :class="fbrEnabled ? 'bg-indigo-600' : 'bg-slate-600'" class="relative inline-flex h-5 w-9 rounded-full transition-colors" :disabled="loading"><span :class="fbrEnabled ? 'translate-x-4' : 'translate-x-0'" class="pointer-events-none inline-block h-4 w-4 rounded-full bg-white shadow mt-0.5 ml-0.5 transition"></span></button><span x-text="fbrEnabled ? 'ON' : 'OFF'" :class="fbrEnabled ? 'text-indigo-400' : 'text-red-400'" class="text-[9px] font-bold"></span></div>
                    <a href="{{ route('fbrpos.create') }}" class="inline-flex items-center gap-1.5 px-4 py-2 bg-indigo-600 text-white text-[11px] font-bold rounded-xl hover:bg-indigo-700 transition"><svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg> New Sale</a>
                </div>
            </div>
            <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-8">
                <div><p class="text-[9px] font-bold text-slate-500 uppercase tracking-wider">Revenue</p><p class="text-2xl font-black text-white mt-1">Rs.{{ number_format($todayStats->revenue ?? 0) }}</p></div>
                <div><p class="text-[9px] font-bold text-slate-500 uppercase tracking-wider">Orders</p><p class="text-2xl font-black text-white mt-1">{{ $todayStats->count ?? 0 }}</p></div>
                <div><p class="text-[9px] font-bold text-slate-500 uppercase tracking-wider">FBR Done</p><p class="text-2xl font-black text-emerald-400 mt-1">{{ $fbrSubmitted }}</p></div>
                <div><p class="text-[9px] font-bold text-slate-500 uppercase tracking-wider">Pending</p><p class="text-2xl font-black text-amber-400 mt-1">{{ $fbrPending }}</p></div>
            </div>
        </div>
    </div>
    @if($company->fbr_pos_id)<div class="bg-indigo-50 dark:bg-indigo-900/20 border border-indigo-200 dark:border-indigo-800 rounded-xl px-4 py-2.5 flex items-center gap-3 fbs-a fbs-2"><div class="w-7 h-7 rounded-lg bg-indigo-600 flex items-center justify-center"><svg class="w-3.5 h-3.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"/></svg></div><p class="text-[10px] font-bold text-indigo-800 dark:text-indigo-300">FBR Integrated — POS #{{ $company->fbr_pos_id }} ({{ ucfirst($company->fbr_pos_environment ?? 'sandbox') }})</p></div>@endif
    <div class="grid grid-cols-3 gap-3 fbs-a fbs-3">
        <div class="fbs-g p-4"><div class="flex items-center gap-2 mb-2"><div class="w-7 h-7 rounded-lg bg-blue-50 dark:bg-blue-900/20 flex items-center justify-center"><svg class="w-3.5 h-3.5 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg></div><p class="text-[8px] text-gray-400 font-bold uppercase">Monthly Revenue</p></div><p class="text-lg font-black text-gray-900 dark:text-white">Rs.{{ number_format($monthStats->revenue ?? 0) }}</p><p class="text-[9px] text-gray-400">{{ $monthStats->count ?? 0 }} txns</p></div>
        <div class="fbs-g p-4"><div class="flex items-center gap-2 mb-2"><div class="w-7 h-7 rounded-lg bg-cyan-50 dark:bg-cyan-900/20 flex items-center justify-center"><svg class="w-3.5 h-3.5 text-cyan-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 14l6-6m-5.5.5h.01m4.99 5h.01M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16l3.5-2 3.5 2 3.5-2 3.5 2z"/></svg></div><p class="text-[8px] text-gray-400 font-bold uppercase">Monthly Tax</p></div><p class="text-lg font-black text-gray-900 dark:text-white">Rs.{{ number_format($monthStats->tax ?? 0) }}</p></div>
        <div class="fbs-g p-4"><div class="flex items-center gap-2 mb-2"><div class="w-7 h-7 rounded-lg bg-emerald-50 dark:bg-emerald-900/20 flex items-center justify-center"><svg class="w-3.5 h-3.5 text-emerald-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 14l6-6m-5.5.5h.01m4.99 5h.01M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16l3.5-2 3.5 2 3.5-2 3.5 2z"/></svg></div><p class="text-[8px] text-gray-400 font-bold uppercase">Today's Tax</p></div><p class="text-lg font-black text-gray-900 dark:text-white">Rs.{{ number_format($todayStats->tax ?? 0) }}</p></div>
    </div>
    <div class="fbs-g overflow-hidden fbs-a fbs-4">
        <div class="px-4 py-3 border-b border-gray-100 dark:border-gray-800/50 flex items-center justify-between"><h3 class="text-[11px] font-bold text-gray-900 dark:text-white uppercase">Transactions</h3><a href="{{ route('fbrpos.transactions') }}" class="text-[10px] font-bold text-indigo-600 dark:text-indigo-400">VIEW ALL</a></div>
        <div class="overflow-x-auto"><table class="w-full"><thead><tr class="bg-gray-50/60 dark:bg-gray-800/30"><th class="text-left text-[9px] text-gray-400 font-bold uppercase py-2 px-4">Invoice</th><th class="text-left text-[9px] text-gray-400 font-bold uppercase py-2 px-3">Customer</th><th class="text-right text-[9px] text-gray-400 font-bold uppercase py-2 px-3">Amount</th><th class="text-center text-[9px] text-gray-400 font-bold uppercase py-2 px-3">FBR</th><th class="text-left text-[9px] text-gray-400 font-bold uppercase py-2 px-4">Date</th></tr></thead><tbody>
            @forelse($recentTransactions as $txn)
            <tr class="border-b border-gray-50 dark:border-gray-800/50 hover:bg-indigo-50/30 transition"><td class="py-2.5 px-4"><a href="{{ route('fbrpos.show', $txn->id) }}" class="text-[11px] font-bold text-indigo-600 dark:text-indigo-400">{{ $txn->invoice_number }}</a></td><td class="py-2.5 px-3 text-[11px] text-gray-600 dark:text-gray-400">{{ $txn->customer_name ?? 'Walk-in' }}</td><td class="py-2.5 px-3 text-right text-[11px] font-black text-gray-900 dark:text-white">Rs.{{ number_format($txn->total_amount, 2) }}</td><td class="py-2.5 px-3 text-center"><span class="text-[8px] font-bold px-1.5 py-0.5 rounded-full {{ $txn->fbr_status === 'submitted' ? 'bg-green-100 text-green-700' : ($txn->fbr_status === 'failed' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700') }}">{{ ucfirst($txn->fbr_status ?? 'pending') }}</span></td><td class="py-2.5 px-4 text-[10px] text-gray-400">{{ $txn->created_at->format('d M h:i A') }}</td></tr>
            @empty<tr><td colspan="5" class="py-8 text-center text-[11px] text-gray-400">No transactions yet</td></tr>@endforelse
        </tbody></table></div>
    </div>
</div>
